# Generated by Django 3.1 on 2021-04-23 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facilities', '0002_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteToVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites_to_visit', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites_to_visit', to='facilities.placetovisit')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteToStay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.BooleanField(default=False)),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites_to_stay', to='facilities.placetostay')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites_to_stay', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteToEat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.BooleanField(default=False)),
                ('eat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites_to_eat', to='facilities.placetoeat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites_to_eat', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
